[package]
name = "raytracer-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
itertools = "0.10.5"
palette = "0.7.1"
png = "0.17.8"
rand = "0.8.5"
rayon = "1.7.0"
